# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-10 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_review', '0002_auto_20180510_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlreviewrecord_old',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='sqlreviewrecord_old',
            name='instance_group',
        ),
        migrations.DeleteModel(
            name='SqlReviewRecord_old',
        ),
    ]
