# Generated by Django 2.0.1 on 2018-06-22 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_review', '0004_querylog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='querylog',
            table='t_query_log',
        ),
    ]
