# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-10 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_auto_20170827_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancerelation',
            name='master_instance',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='master_instance_id', to='statistics.MysqlInstance', verbose_name='\u4e3bid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instancerelation',
            name='slave_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slave_instance_id', to='statistics.MysqlInstance', verbose_name='\u4eceid'),
            preserve_default=False,
        ),
    ]
